name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Generate PDF and Word files
        run: |
          mkdir output
          for file in *.md; do
            pandoc -s -o output/${file%.md}.pdf $file
            pandoc -s -o output/${file%.md}.docx $file
          done

      - name: Deploy files
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output
