name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-latex-extra

      - name: Generate PDF and Word files
        run: |
          mkdir -p output
          find . -name "*.md" | while read file; do
            dir=$(dirname "$file")
            filename=$(basename "$file" .md)
            mkdir -p "output/$dir"
            pandoc -s -o "output/${dir}/${filename}.pdf" "$file"
            pandoc -s -o "output/${dir}/${filename}.docx" "$file"
          done

      - name: Deploy files
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output
